/**
 * ocrapi
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveOcrApiClient);
  }
}(this, function(expect, CloudmersiveOcrApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveOcrApiClient.OcrLineElement();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OcrLineElement', function() {
    it('should create an instance of OcrLineElement', function() {
      // uncomment below and update the code to test OcrLineElement
      //var instane = new CloudmersiveOcrApiClient.OcrLineElement();
      //expect(instance).to.be.a(CloudmersiveOcrApiClient.OcrLineElement);
    });

    it('should have the property lineText (base name: "LineText")', function() {
      // uncomment below and update the code to test the property lineText
      //var instane = new CloudmersiveOcrApiClient.OcrLineElement();
      //expect(instance).to.be();
    });

    it('should have the property words (base name: "Words")', function() {
      // uncomment below and update the code to test the property words
      //var instane = new CloudmersiveOcrApiClient.OcrLineElement();
      //expect(instance).to.be();
    });

  });

}));
